<a href="https://colab.research.google.com/github/cmb170230/Portfolio/blob/main/Adaboost%20Classifier%20with%20UCI%20Heart%20Disease%20Dataset/AdaBoost_Classification_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving heart_test.data to heart_test.data
Saving heart_train.data to heart_train.data


In [ ]:
import io
tr_df = pd.read_csv(io.BytesIO(uploaded['heart_train.data']), header=None, index_col = False)
te_df = pd.read_csv(io.BytesIO(uploaded['heart_test.data']), header=None, index_col= False)
train = tr_df.to_numpy()
test = te_df.to_numpy()
x_train = train[:,1:]
y_train = train[:,0]
x_test = test[:,1:]
y_test = test[:,0]

print(x_train, y_train)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 1]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 1]
 [1 0 0 ... 0 0 0]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [ ]:
##Structure
#construct trees (tree/node class)
#classify/update weight sum
#compute alpha
#update weights

#construct hypotheses
#for each possible decision tree, find vals for leaf by majority vote
class Node:
  def __init__(self):
    self.attr = None
    self.attrVal = None
    self.child1 = None
    self.child2 = None
  def __init__(self, attr, attrVal):
    self.attr = attr
    self.attrVal = attrVal
    self.child1 = None
    self.child2 = None

class DecisionTree:
  def __init__(self, head):
    self.head = head



In [ ]:
##TRASH DO NOT RUN
#decisionList = list()

#for i in range(1, x_train.shape[1]+1):
  #for j in range(1, x_train.shape[1]+1):
    #decisionList.append(DecisionTree(Node(i,0)))
    #decisionList[i+j].head.child1 = Node(j, 0)
    #decisionList[i+j].head.child2 = Node(j, 1)
    #decisionList.append(DecisionTree(Node(i,1)))
    #decisionList[i+1].head.child1 = Node(j, 0)
    #decisionList[i+1].head.child2 = Node(j, 1)
#len(decisionList)



In [ ]:
#Generates all possible trees and stores them in a list
#node with attribute -1: head node
#node with attribute -2: label assigned to a node
import copy
count = 0
treeList = list()
for i in range(0, x_train.shape[1]):
  #create all possible first splits
  tree = DecisionTree(Node(-1, -1))
  tree.head.child1 = Node(i, 1)
  tree.head.child2 = Node(i, 0)
  for j in range(0, x_train.shape[1]):
    #create all possible left-hand splits
    copy1 = copy.deepcopy(tree)
    copy1.head.child1.child1 = Node(j, 0)
    copy1.head.child1.child2 = Node(j, 1)
    #treeList.append(copy1)
    for k in range(8):
      #create all labelings for each split
      copy2 = copy.deepcopy(copy1)
      if(k < 4):
        copy2.head.child1.child1.child1 = Node(-2, 0)
      else:
        copy2.head.child1.child1.child1 = Node(-2, 1)
      if(k < 2 or (k >= 4 and k < 6)):
        copy2.head.child1.child2.child1 = Node(-2, 0)
      else:
        copy2.head.child1.child2.child1 = Node(-2, 1)
      copy2.head.child2.child1 = Node(-2, k%2)
      treeList.append(copy2)
  for j in range(0, x_train.shape[1]):
    #create all possible right-hand splits
    copy1_1 = copy.deepcopy(tree)
    copy1_1.head.child2.child1 = Node(j, 0)
    copy1_1.head.child2.child2 = Node(j, 1)
    #treeList.append(copy1_1)
    for k in range(8):
      #create all possible labelings for each split
      copy2_1 = copy.deepcopy(copy1_1)
      if(k < 4):
        copy2_1.head.child2.child1.child1 = Node(-2, 0)
      else:
        copy2_1.head.child2.child1.child1 = Node(-2, 1)
      if(k < 2 or (k >= 4 and k < 6)):
        copy2_1.head.child2.child2.child1 = Node(-2, 0)
      else:
        copy2_1.head.child2.child2.child1 = Node(-2, 1)
      copy2_1.head.child1.child1 = Node(-2, k%2)
      treeList.append(copy2_1)
print("# of trees constructed:", len(treeList))
print("22^2*8*2= ", 22*22*8*2)

# of trees constructed: 7744
22^2*8*2=  7744


In [ ]:
#debug: look at a given tree in detail
examine = treeList[2587]
print(examine.head.attr, examine.head.attrVal)
examine1_1 = examine.head.child1
print(examine1_1.attr, examine1_1.attrVal)
if(examine1_1.child1.attr != -2):
  print(examine1_1.child1.attr, examine1_1.child1.attrVal)
  print(examine1_1.child2.attr, examine1_1.child2.attrVal)
  print(examine1_1.child1.child1.attr, examine1_1.child1.child1.attrVal)
  print(examine1_1.child2.child1.attr, examine1_1.child2.child1.attrVal)
else:
  print(examine1_1.child1.attr, examine1_1.child1.attrVal)
examine1_2 = examine.head.child2
print(examine1_2.attr, examine1_2.attrVal)
if(examine1_2.child1.attr != -2):
  print(examine1_2.child1.attr, examine1_2.child1.attrVal)
  print(examine1_2.child2.attr, examine1_2.child2.attrVal)
  print(examine1_2.child1.child1.attr, examine1_2.child1.child1.attrVal)
  print(examine1_2.child2.child1.attr, examine1_2.child2.child1.attrVal)
else:
  print(examine1_2.child1.attr, examine1_2.child1.attrVal)

-1 -1
7 1
15 0
15 1
-2 0
-2 1
7 0
-2 1


In [ ]:
#indicator function
def indicator(dtree, datapoint, yval):
  #find the first attribute to check the split on
  split1 = dtree.head.child1.attr
  dataVal1 = datapoint[split1]
  label = None
  #if the tree is left-handed and the left side should be searched
  if(dataVal1 == 0 and dtree.head.child1.child1.attr != -2):
    l1 = 0
    split2 = dtree.head.child1.child1.attr
    dataVal2 = datapoint[split2]
    #if the predicted label is on the left child
    if(dataVal2 == 0):
      l2 = 0
      label = dtree.head.child1.child1.child1.attrVal
    #if the predicted label is on the right child
    else:
      l2 = 1
      label = dtree.head.child1.child2.child1.attrVal
  #if the tree is right handed and the right side should be searched
  elif(dataVal1 == 1 and dtree.head.child2.child1.attr != -2):
    l1 = 1
    split2 = dtree.head.child2.child1.attr
    dataVal2 = datapoint[split2]
    #if the predicted label is on the left child
    if(dataVal2 == 0):
      l2 = 0
      label = dtree.head.child2.child1.child1.attrVal
    #if the predicted label is on the right child
    else:
      l2 = 1
      label = dtree.head.child2.child2.child1.attrVal
  #if the tree is right-handed and the predicted label is on the left
  elif(dataVal1 == 0):
    l1 = 0
    l2 = -1
    label = dtree.head.child1.child1.attrVal
  #if the tree is left-handed and the predicted label is on the right
  elif(dataVal1 == 1):
    l1 = 1
    l2 = -1
    label = dtree.head.child2.child1.attrVal
  else:
    l1 = -1
    l2 = -1
    return None
  #if it is correctly classified, return 0, else return 1 (returning of label for weight updates)
  if(label == yval):
   # print(l1, split1, l2)
    return 0, label
  else:
   # print(l1, split1, l2)
    #if(l2 >= 0):
   #   print(split2)
    return 1, label   

In [ ]:
#indicator attempt 2
def indicator2(dtree, datapoint, yval):
  split1 = dtree.head.child1.attr
  dataVal1 = datapoint[split1]
  searchNode = dtree.head.child1
  if(dataVal1 == 0):
    if(searchNode.child1.attr!= -2):
      split2 = searchNode.child1.attr
      dataVal2 = datapoint[split2]
      if(dataVal2 == 0):
        label = searchNode.child1.child1.attrVal
      elif(dataVal2 == 1):
        label = searchNode.child2.child1.attrVal
    elif(searchNode.child1.attr == -2):
      label = searchNode.child1.attrVal
  elif(dataVal1 == 1):
    searchNode_1 = dtree.head.child2
    if(searchNode_1.child1.attr != -2):
      split2_1 = searchNode.child1.attr
      dataVal2_1 = datapoint[split2_1]
      if(dataVal2_1 == 0):
        label = searchNode_1.child1.child1.attrVal
      elif(dataVal2_1 == 1):
        label = searchNode_1.child2.child1.attrVal
    elif(searchNode_1.child1.attr == -2):
      label = searchNode.child1.attrVal
  if(label == yval):
    return 0, label
  elif(label != yval):
    return 1, label

In [ ]:
#brief check to see if above function is working properly
testpt = 32
print(indicator(treeList[6800], x_train[testpt,:], y_train[testpt]), y_train[testpt])



(1, 0) 1


In [ ]:
from numpy.core.getlimits import inf
#find minimum error
def minError(x_dataset, y_dataset, listOfTrees, weights):
  errList = list()
  #initialize min error found to infinity, no best tree yet
  minError = inf
  bestTree = None
  #for each possible classifier
  for i in range(len(listOfTrees)):
    error = 0
    #sum the weighted error
    for j in range(0,x_dataset.shape[0]):
      indVal,pred = indicator(listOfTrees[i], x_dataset[j,:], y_dataset[j])
      if(pred^y_dataset[j]!=indVal):
        print("Error:", j)
      error += weights[j]*indVal
    errList.append(error)
    #if the error found is less than the previous best, keep track of the error and tree
    #if(error < minError):
    #  minError = error
    #  bestTree = listOfTrees[i]
  minError = min(errList)
  bestTree = listOfTrees[errList.index(minError)]
  maxError = max(errList)
  bestTreeInv = listOfTrees[errList.index(maxError)]

  return minError, bestTree, maxError, bestTreeInv

In [ ]:
#test of above function before writing full adaBoost
weightArr = np.arange(x_train.shape[0], dtype=float)
for i in range(x_train.shape[0]):
  weightArr[i] = 1/x_train.shape[0]
output = minError(x_train, y_train, treeList, weightArr)
print(output)
print(output[0] + output[2])

(0.21250000000000005, <__main__.DecisionTree object at 0x7f52d7f1ac70>, 0.7874999999999992, <__main__.DecisionTree object at 0x7f52d7f1afd0>)
0.9999999999999992


In [ ]:
#check to see if the tree being found exhibits odd behavior (only selects extremes, etc.)
for i in range(len(treeList)):
  if (treeList[i] == output[1]):
    print(i)

3619


In [ ]:
from math import log, exp, sqrt
def adaBoost(x_data, y_data, max_iter):
  #initialize all weights to be equal
  flipPred = 1
  weightArr = np.arange(x_data.shape[0], dtype=float)
  for i in range(x_data.shape[0]):
      weightArr[i] = 1/x_data.shape[0]
  elist = list()
  alphalist = list()
  bestTreeList = list()
  weightList = list()
  flipped = list()
  for i in range(max_iter):
    #find e_t and tree for the given iteration
    output = minError(x_data, y_data, treeList, weightArr)
    minE = output[0]
    maxE = 1-output[2]
    if(maxE > minE or maxE <= 0 or maxE >= 1):
      err = output[0]
      bestTr = output[1]
    else:
      flipPred = -1
      err = 1-output[2]
      bestTr = output[3]
    elist.append(err)
    bestTreeList.append(bestTr)

    #calculate alpha_t
    print(err)
    alpha = 0.5*log((1-err)/err)
    alphalist.append(alpha)
    #print(alpha)
    #update the weights
    weightList.append(copy.deepcopy(weightArr))
    for j in range(x_data.shape[0]):
      pred = indicator(bestTr, x_data[j,:], y_data[j])
      if(pred[1] == 0):
        h_t_x = -1*flipPred
      else:
        h_t_x = 1*flipPred
      w = weightArr[j]
      adjust = exp((-1*y_data[j]*h_t_x*alpha))
      normalize = 2*sqrt(err*(1-err))
      weightArr[j] = (w*adjust)/normalize
      #weightArr[j] = (weightArr[j] * exp(-y_data[j]*h_t_x*alpha))/(2*sqrt(output[0]*(1-output[0])))

    #debug: check that weight sums == 1
    sum = 0
    for j in range(weightArr.shape[0]):
      sum += weightArr[j]
    print(sum)

    flipped.append(flipPred)

  return elist, alphalist, bestTreeList, weightList, flipped

In [ ]:
from math import log, exp, sqrt
def adaBoost_prev(x_data, y_data, max_iter):
  #initialize all weights to be equal
  weightArr = np.arange(x_data.shape[0], dtype=float)
  for i in range(x_data.shape[0]):
      weightArr[i] = 1/x_data.shape[0]
  elist = list()
  alphalist = list()
  bestTreeList = list()
  weightList = list()
  flipped = list()
  for i in range(max_iter):
    #find e_t and tree for the given iteration
    output = minError(x_data, y_data, treeList, weightArr)
    err = output[0]
    bestTr = output[1]
    elist.append(err)
    bestTreeList.append(bestTr)

    #calculate alpha_t
    print(err)
    alpha = 0.5*log((1-err)/err)
    alphalist.append(alpha)
    #print(alpha)
    #update the weights
    weightList.append(copy.deepcopy(weightArr))
    recalculated_e = 0 #
    for j in range(x_data.shape[0]):
      pred = indicator(bestTr, x_data[j,:], y_data[j])
      if(pred[1] == 0):
        h_t_x = -1
      else:
        h_t_x = 1

      w = weightArr[j]
      if(y_data[j] == 0):
        y = -1
      else:
        y = 1
      adjust = exp((-1*y*h_t_x*alpha))
      normalize = 2*sqrt(err*(1-err))
      weightArr[j] = (w*adjust)/normalize
      #weightArr[j] = (weightArr[j] * exp(-y_data[j]*h_t_x*alpha))/(2*sqrt(output[0]*(1-output[0])))

    #debug: check that weight sums == 1
    sum = 0
    for j in range(weightArr.shape[0]):
      sum += weightArr[j]
    print(sum)

    flipped.append(1)

  return elist, alphalist, bestTreeList, weightList, flipped

In [ ]:
#snippet to solve the problem of forgetting to change 0 labels to -1
pred = indicator(treeList[2353], x_train[34,:], y_train[34])
print(pred)
if(pred[0] == 0):
  h_t_x = -1
else:
  h_t_x = 1;
h_t_x

(0, 1)


-1

In [ ]:
e_l, a_l, bT_l, w_l, f_l = adaBoost_prev(x_train, y_train, 5)

0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.3073301040034191
1.0000000000000007
0.3609222826701768
1.0000000000000009


In [ ]:
a_l

[0.6549606911676581,
 0.37843149747302635,
 0.2734972663157064,
 0.4063155589491071,
 0.2856817093262064,
 0.2774279006301844,
 0.21206052926298508,
 0.2939608813087992,
 0.21569500159199742,
 0.17234529706890792]

In [ ]:
bT_l
for i in range(len(bT_l)):
  for j in range(len(treeList)):
   if (treeList[j] == bT_l[i]):
    print(j)


3619
1227
1035
2587
1035


In [ ]:
#construct classifier
def classify(x_datum, y_datum, alist, bTr):
  label = 0
  for i in range(len(bTr)):
    out = indicator(bTr[i], x_datum, y_datum)
    pred = out[1]
    if(pred == 0):
      pred = -1
    label += alist[i]*pred
  return np.sign(label)

def accuracy(x_data, y_data, alist, bTr):
  acc = 1
  misCount = 0
  for i in range(len(x_data)):
    classifyLabel = classify(x_data[i,:], y_data[i], alist, bTr)
    if(classifyLabel == -1):
      classifyLabel = 0
    if(classifyLabel != y_data[i]):
      misCount += 1
  return 1 - (misCount / x_data.shape[0])

In [ ]:
print(accuracy(x_train, y_train, a_l, bT_l))
print(accuracy(x_test, y_test, a_l, bT_l))

0.8125
0.7647058823529411


In [ ]:
#generate ouput for graphs
rounds = 10
accTrainl = list()
accTestl = list()
for i in range(1, rounds+1):
  e_l, a_l, bT_l, w_l, f_l = adaBoost_prev(x_train, y_train, i)
  accTrainl.append(accuracy(x_train, y_train, a_l, bT_l))
  accTestl.append(accuracy(x_test, y_test, a_l, bT_l))


0.21250000000000005
0.9999999999999993
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.3073301040034191
1.0000000000000007
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.3073301040034191
1.0000000000000007
0.3609222826701768
1.0000000000000009
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.3073301040034191
1.0000000000000007
0.3609222826701768
1.0000000000000009
0.3647385614997371
1.0
0.21250000000000005
0.9999999999999993
0.31932773109243706
1.0000000000000007
0.3665619810843981
1.0000000000000009
0.3073301040034191
1.0000000000000007
0.3609222826701768
1.0000000000000009
0.364738561499

In [ ]:
print(accTrainl, "\n", accTestl)

[0.7875, 0.7875, 0.7875, 0.8125, 0.8125, 0.825, 0.8625, 0.8625, 0.8625, 0.8625] 
 [0.7112299465240641, 0.7112299465240641, 0.7112299465240641, 0.7647058823529411, 0.7647058823529411, 0.786096256684492, 0.786096256684492, 0.786096256684492, 0.7754010695187166, 0.7700534759358288]
